# Generated by Django 4.1.5 on 2024-04-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_venta_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tax_percentage',
            field=models.FloatField(default=16),
        ),
    ]
